dictionary BlobPropertyBag {
  DOMString type_ = "";
};

[Constructor(optional sequence<BlobPart> blobParts, optional BlobPropertyBag options),
Exposed=(Window,Worker)]
interface Blob {

  readonly attribute unsigned long long size;
  readonly attribute DOMString type_; // FIXME: escape keyword like "type" rather than modify it
  readonly attribute boolean isClosed;

  //slice Blob into byte-ranged chunks

  Blob slice([Clamp] optional long long start,
            [Clamp] optional long long end,
            optional DOMString contentType);
  void close();

};

typedef (BufferSource or Blob or USVString) BlobPart;
